server:
  port:
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: http://localhost:3306/domainswitcher
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        slave:
          url: http://localhost:3306/domainswitcher
          username: root
          password: root
          driver-clss-name: com.mysql.jdbc.Driver
  application:
    name: sysmanager-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null