server:
  port: 9876
spring:
  datasource:
    dynamic:
      hikari:
        idle-timeout: 600000
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 10
        min-idle: 2
      primary: domainswitcher
      strict: false
      datasource:
        domainswitcher:
          url: jdbc:mysql://localhost:3306/domainswitcher?useSSL=false&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        domainnamechecker:
          url: jdbc:mysql://localhost:3306/domainnamechecker?useSSL=false&serverTimezone=UTC
          username: root
          password: root
          driver-clss-name: com.mysql.cj.jdbc.Driver

  application:
    name: sysmanager-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.moyun.sysmanager.domainnamechecker.entity,com.moyun.sysmanager.domainswitcher.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false